default_chain: stride-testnet
chains:
  gaia-testnet:
    key: icq-gaia
    chain-id: GAIA
    rpc-addr: http://95.214.55.4:26667
    grpc-addr: http://95.214.55.4:9092
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: icq-stride
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://127.0.0.1:26657
    grpc-addr: http://127.0.0.1:36657
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
